// Generated by gencpp from file your_smach/GoToPosition.msg
// DO NOT EDIT!


#ifndef YOUR_SMACH_MESSAGE_GOTOPOSITION_H
#define YOUR_SMACH_MESSAGE_GOTOPOSITION_H

#include <ros/service_traits.h>


#include <your_smach/GoToPositionRequest.h>
#include <your_smach/GoToPositionResponse.h>


namespace your_smach
{

struct GoToPosition
{

typedef GoToPositionRequest Request;
typedef GoToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPosition
} // namespace your_smach


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_smach::GoToPosition > {
  static const char* value()
  {
    return "b2053259e93d06245bdd1477ed5595a1";
  }

  static const char* value(const ::your_smach::GoToPosition&) { return value(); }
};

template<>
struct DataType< ::your_smach::GoToPosition > {
  static const char* value()
  {
    return "your_smach/GoToPosition";
  }

  static const char* value(const ::your_smach::GoToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::your_smach::GoToPositionRequest> should match
// service_traits::MD5Sum< ::your_smach::GoToPosition >
template<>
struct MD5Sum< ::your_smach::GoToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_smach::GoToPosition >::value();
  }
  static const char* value(const ::your_smach::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_smach::GoToPositionRequest> should match
// service_traits::DataType< ::your_smach::GoToPosition >
template<>
struct DataType< ::your_smach::GoToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::your_smach::GoToPosition >::value();
  }
  static const char* value(const ::your_smach::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_smach::GoToPositionResponse> should match
// service_traits::MD5Sum< ::your_smach::GoToPosition >
template<>
struct MD5Sum< ::your_smach::GoToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_smach::GoToPosition >::value();
  }
  static const char* value(const ::your_smach::GoToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_smach::GoToPositionResponse> should match
// service_traits::DataType< ::your_smach::GoToPosition >
template<>
struct DataType< ::your_smach::GoToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::your_smach::GoToPosition >::value();
  }
  static const char* value(const ::your_smach::GoToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_SMACH_MESSAGE_GOTOPOSITION_H
