// Generated by gencpp from file your_smach/GoToPositionResponse.msg
// DO NOT EDIT!


#ifndef YOUR_SMACH_MESSAGE_GOTOPOSITIONRESPONSE_H
#define YOUR_SMACH_MESSAGE_GOTOPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_smach
{
template <class ContainerAllocator>
struct GoToPositionResponse_
{
  typedef GoToPositionResponse_<ContainerAllocator> Type;

  GoToPositionResponse_()
    : success(false)  {
    }
  GoToPositionResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::your_smach::GoToPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_smach::GoToPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPositionResponse_

typedef ::your_smach::GoToPositionResponse_<std::allocator<void> > GoToPositionResponse;

typedef boost::shared_ptr< ::your_smach::GoToPositionResponse > GoToPositionResponsePtr;
typedef boost::shared_ptr< ::your_smach::GoToPositionResponse const> GoToPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_smach::GoToPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_smach::GoToPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::your_smach::GoToPositionResponse_<ContainerAllocator1> & lhs, const ::your_smach::GoToPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::your_smach::GoToPositionResponse_<ContainerAllocator1> & lhs, const ::your_smach::GoToPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace your_smach

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_smach::GoToPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::GoToPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::GoToPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::your_smach::GoToPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_smach/GoToPositionResponse";
  }

  static const char* value(const ::your_smach::GoToPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::your_smach::GoToPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_smach::GoToPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::your_smach::GoToPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_SMACH_MESSAGE_GOTOPOSITIONRESPONSE_H
