// Generated by gencpp from file your_smach/triggerResponse.msg
// DO NOT EDIT!


#ifndef YOUR_SMACH_MESSAGE_TRIGGERRESPONSE_H
#define YOUR_SMACH_MESSAGE_TRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_smach
{
template <class ContainerAllocator>
struct triggerResponse_
{
  typedef triggerResponse_<ContainerAllocator> Type;

  triggerResponse_()
    : ans()  {
    }
  triggerResponse_(const ContainerAllocator& _alloc)
    : ans(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ans_type;
  _ans_type ans;





  typedef boost::shared_ptr< ::your_smach::triggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_smach::triggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct triggerResponse_

typedef ::your_smach::triggerResponse_<std::allocator<void> > triggerResponse;

typedef boost::shared_ptr< ::your_smach::triggerResponse > triggerResponsePtr;
typedef boost::shared_ptr< ::your_smach::triggerResponse const> triggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_smach::triggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_smach::triggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::your_smach::triggerResponse_<ContainerAllocator1> & lhs, const ::your_smach::triggerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ans == rhs.ans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::your_smach::triggerResponse_<ContainerAllocator1> & lhs, const ::your_smach::triggerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace your_smach

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_smach::triggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_smach::triggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::triggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::triggerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::triggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::triggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_smach::triggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65c770945c83e7be8dd04ade02be6046";
  }

  static const char* value(const ::your_smach::triggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65c770945c83e7beULL;
  static const uint64_t static_value2 = 0x8dd04ade02be6046ULL;
};

template<class ContainerAllocator>
struct DataType< ::your_smach::triggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_smach/triggerResponse";
  }

  static const char* value(const ::your_smach::triggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_smach::triggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ans\n"
"\n"
;
  }

  static const char* value(const ::your_smach::triggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_smach::triggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct triggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_smach::triggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::your_smach::triggerResponse_<ContainerAllocator>& v)
  {
    s << indent << "ans: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ans);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_SMACH_MESSAGE_TRIGGERRESPONSE_H
