// Generated by gencpp from file your_smach/triggerRequest.msg
// DO NOT EDIT!


#ifndef YOUR_SMACH_MESSAGE_TRIGGERREQUEST_H
#define YOUR_SMACH_MESSAGE_TRIGGERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace your_smach
{
template <class ContainerAllocator>
struct triggerRequest_
{
  typedef triggerRequest_<ContainerAllocator> Type;

  triggerRequest_()
    {
    }
  triggerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::your_smach::triggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::your_smach::triggerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct triggerRequest_

typedef ::your_smach::triggerRequest_<std::allocator<void> > triggerRequest;

typedef boost::shared_ptr< ::your_smach::triggerRequest > triggerRequestPtr;
typedef boost::shared_ptr< ::your_smach::triggerRequest const> triggerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::your_smach::triggerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::your_smach::triggerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace your_smach

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::your_smach::triggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::your_smach::triggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::triggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::your_smach::triggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::triggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::your_smach::triggerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::your_smach::triggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::your_smach::triggerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::your_smach::triggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "your_smach/triggerRequest";
  }

  static const char* value(const ::your_smach::triggerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::your_smach::triggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::your_smach::triggerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::your_smach::triggerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct triggerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::your_smach::triggerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::your_smach::triggerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // YOUR_SMACH_MESSAGE_TRIGGERREQUEST_H
