// Generated by gencpp from file ku_arm_belt_driver/GoToArmPoseResponse.msg
// DO NOT EDIT!


#ifndef KU_ARM_BELT_DRIVER_MESSAGE_GOTOARMPOSERESPONSE_H
#define KU_ARM_BELT_DRIVER_MESSAGE_GOTOARMPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ku_arm_belt_driver
{
template <class ContainerAllocator>
struct GoToArmPoseResponse_
{
  typedef GoToArmPoseResponse_<ContainerAllocator> Type;

  GoToArmPoseResponse_()
    : success(false)  {
    }
  GoToArmPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToArmPoseResponse_

typedef ::ku_arm_belt_driver::GoToArmPoseResponse_<std::allocator<void> > GoToArmPoseResponse;

typedef boost::shared_ptr< ::ku_arm_belt_driver::GoToArmPoseResponse > GoToArmPoseResponsePtr;
typedef boost::shared_ptr< ::ku_arm_belt_driver::GoToArmPoseResponse const> GoToArmPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator1> & lhs, const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator1> & lhs, const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ku_arm_belt_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ku_arm_belt_driver/GoToArmPoseResponse";
  }

  static const char* value(const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToArmPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ku_arm_belt_driver::GoToArmPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KU_ARM_BELT_DRIVER_MESSAGE_GOTOARMPOSERESPONSE_H
