// Generated by gencpp from file ku_arm_belt_driver/SaveArmPoseRequest.msg
// DO NOT EDIT!


#ifndef KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSEREQUEST_H
#define KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ku_arm_belt_driver
{
template <class ContainerAllocator>
struct SaveArmPoseRequest_
{
  typedef SaveArmPoseRequest_<ContainerAllocator> Type;

  SaveArmPoseRequest_()
    : pose_name()  {
    }
  SaveArmPoseRequest_(const ContainerAllocator& _alloc)
    : pose_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pose_name_type;
  _pose_name_type pose_name;





  typedef boost::shared_ptr< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveArmPoseRequest_

typedef ::ku_arm_belt_driver::SaveArmPoseRequest_<std::allocator<void> > SaveArmPoseRequest;

typedef boost::shared_ptr< ::ku_arm_belt_driver::SaveArmPoseRequest > SaveArmPoseRequestPtr;
typedef boost::shared_ptr< ::ku_arm_belt_driver::SaveArmPoseRequest const> SaveArmPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator1> & lhs, const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose_name == rhs.pose_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator1> & lhs, const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ku_arm_belt_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6184073e8e665fb2bf0be194fc36541";
  }

  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6184073e8e665fbULL;
  static const uint64_t static_value2 = 0x2bf0be194fc36541ULL;
};

template<class ContainerAllocator>
struct DataType< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ku_arm_belt_driver/SaveArmPoseRequest";
  }

  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pose_name\n"
;
  }

  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveArmPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ku_arm_belt_driver::SaveArmPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pose_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSEREQUEST_H
