// Generated by gencpp from file ku_arm_belt_driver/SaveArmPose.msg
// DO NOT EDIT!


#ifndef KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSE_H
#define KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSE_H

#include <ros/service_traits.h>


#include <ku_arm_belt_driver/SaveArmPoseRequest.h>
#include <ku_arm_belt_driver/SaveArmPoseResponse.h>


namespace ku_arm_belt_driver
{

struct SaveArmPose
{

typedef SaveArmPoseRequest Request;
typedef SaveArmPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveArmPose
} // namespace ku_arm_belt_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ku_arm_belt_driver::SaveArmPose > {
  static const char* value()
  {
    return "79d88096a3ed8bf571f433b49f30cb27";
  }

  static const char* value(const ::ku_arm_belt_driver::SaveArmPose&) { return value(); }
};

template<>
struct DataType< ::ku_arm_belt_driver::SaveArmPose > {
  static const char* value()
  {
    return "ku_arm_belt_driver/SaveArmPose";
  }

  static const char* value(const ::ku_arm_belt_driver::SaveArmPose&) { return value(); }
};


// service_traits::MD5Sum< ::ku_arm_belt_driver::SaveArmPoseRequest> should match
// service_traits::MD5Sum< ::ku_arm_belt_driver::SaveArmPose >
template<>
struct MD5Sum< ::ku_arm_belt_driver::SaveArmPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ku_arm_belt_driver::SaveArmPose >::value();
  }
  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ku_arm_belt_driver::SaveArmPoseRequest> should match
// service_traits::DataType< ::ku_arm_belt_driver::SaveArmPose >
template<>
struct DataType< ::ku_arm_belt_driver::SaveArmPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ku_arm_belt_driver::SaveArmPose >::value();
  }
  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ku_arm_belt_driver::SaveArmPoseResponse> should match
// service_traits::MD5Sum< ::ku_arm_belt_driver::SaveArmPose >
template<>
struct MD5Sum< ::ku_arm_belt_driver::SaveArmPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ku_arm_belt_driver::SaveArmPose >::value();
  }
  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ku_arm_belt_driver::SaveArmPoseResponse> should match
// service_traits::DataType< ::ku_arm_belt_driver::SaveArmPose >
template<>
struct DataType< ::ku_arm_belt_driver::SaveArmPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ku_arm_belt_driver::SaveArmPose >::value();
  }
  static const char* value(const ::ku_arm_belt_driver::SaveArmPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KU_ARM_BELT_DRIVER_MESSAGE_SAVEARMPOSE_H
