(cl:defpackage ku_arm_belt_driver-srv
  (:use )
  (:export
   "GOTOARMPOSE"
   "<GOTOARMPOSE-REQUEST>"
   "GOTOARMPOSE-REQUEST"
   "<GOTOARMPOSE-RESPONSE>"
   "GOTOARMPOSE-RESPONSE"
   "SAVEARMPOSE"
   "<SAVEARMPOSE-REQUEST>"
   "SAVEARMPOSE-REQUEST"
   "<SAVEARMPOSE-RESPONSE>"
   "SAVEARMPOSE-RESPONSE"
  ))

