controller_list:
 - name: panda_arm_controller
   type: FollowJointTrajectory
   default: true
   joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
 - name: hand_controller
   action_ns: gripper_action
   type: GripperCommand
   default: true
   parallel: true
   joints:
     - joint6_1
     - joint6_2
     - joint7_1
     - joint7_2