controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint6_1
  - name: fake_crma_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses per group
#  - group: gripper
#    pose: home

  []