(cl:defpackage your_package-srv
  (:use )
  (:export
   "NAVTOLOCATION"
   "<NAVTOLOCATION-REQUEST>"
   "NAVTOLOCATION-REQUEST"
   "<NAVTOLOCATION-RESPONSE>"
   "NAVTOLOCATION-RESPONSE"
   "SAVELOCATION"
   "<SAVELOCATION-REQUEST>"
   "SAVELOCATION-REQUEST"
   "<SAVELOCATION-RESPONSE>"
   "SAVELOCATION-RESPONSE"
  ))

