// Generated by gencpp from file donkey_car/DriveMode.msg
// DO NOT EDIT!


#ifndef DONKEY_CAR_MESSAGE_DRIVEMODE_H
#define DONKEY_CAR_MESSAGE_DRIVEMODE_H

#include <ros/service_traits.h>


#include <donkey_car/DriveModeRequest.h>
#include <donkey_car/DriveModeResponse.h>


namespace donkey_car
{

struct DriveMode
{

typedef DriveModeRequest Request;
typedef DriveModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveMode
} // namespace donkey_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::donkey_car::DriveMode > {
  static const char* value()
  {
    return "e4da47a0d835738660a86a1db5528f89";
  }

  static const char* value(const ::donkey_car::DriveMode&) { return value(); }
};

template<>
struct DataType< ::donkey_car::DriveMode > {
  static const char* value()
  {
    return "donkey_car/DriveMode";
  }

  static const char* value(const ::donkey_car::DriveMode&) { return value(); }
};


// service_traits::MD5Sum< ::donkey_car::DriveModeRequest> should match
// service_traits::MD5Sum< ::donkey_car::DriveMode >
template<>
struct MD5Sum< ::donkey_car::DriveModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::DriveMode >::value();
  }
  static const char* value(const ::donkey_car::DriveModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::DriveModeRequest> should match
// service_traits::DataType< ::donkey_car::DriveMode >
template<>
struct DataType< ::donkey_car::DriveModeRequest>
{
  static const char* value()
  {
    return DataType< ::donkey_car::DriveMode >::value();
  }
  static const char* value(const ::donkey_car::DriveModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::donkey_car::DriveModeResponse> should match
// service_traits::MD5Sum< ::donkey_car::DriveMode >
template<>
struct MD5Sum< ::donkey_car::DriveModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::DriveMode >::value();
  }
  static const char* value(const ::donkey_car::DriveModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::DriveModeResponse> should match
// service_traits::DataType< ::donkey_car::DriveMode >
template<>
struct DataType< ::donkey_car::DriveModeResponse>
{
  static const char* value()
  {
    return DataType< ::donkey_car::DriveMode >::value();
  }
  static const char* value(const ::donkey_car::DriveModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DONKEY_CAR_MESSAGE_DRIVEMODE_H
