// Generated by gencpp from file donkey_car/IntValue.msg
// DO NOT EDIT!


#ifndef DONKEY_CAR_MESSAGE_INTVALUE_H
#define DONKEY_CAR_MESSAGE_INTVALUE_H

#include <ros/service_traits.h>


#include <donkey_car/IntValueRequest.h>
#include <donkey_car/IntValueResponse.h>


namespace donkey_car
{

struct IntValue
{

typedef IntValueRequest Request;
typedef IntValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IntValue
} // namespace donkey_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::donkey_car::IntValue > {
  static const char* value()
  {
    return "0f0a503a6dfd41f41ab6b6db4044064a";
  }

  static const char* value(const ::donkey_car::IntValue&) { return value(); }
};

template<>
struct DataType< ::donkey_car::IntValue > {
  static const char* value()
  {
    return "donkey_car/IntValue";
  }

  static const char* value(const ::donkey_car::IntValue&) { return value(); }
};


// service_traits::MD5Sum< ::donkey_car::IntValueRequest> should match
// service_traits::MD5Sum< ::donkey_car::IntValue >
template<>
struct MD5Sum< ::donkey_car::IntValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::IntValue >::value();
  }
  static const char* value(const ::donkey_car::IntValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::IntValueRequest> should match
// service_traits::DataType< ::donkey_car::IntValue >
template<>
struct DataType< ::donkey_car::IntValueRequest>
{
  static const char* value()
  {
    return DataType< ::donkey_car::IntValue >::value();
  }
  static const char* value(const ::donkey_car::IntValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::donkey_car::IntValueResponse> should match
// service_traits::MD5Sum< ::donkey_car::IntValue >
template<>
struct MD5Sum< ::donkey_car::IntValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::IntValue >::value();
  }
  static const char* value(const ::donkey_car::IntValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::IntValueResponse> should match
// service_traits::DataType< ::donkey_car::IntValue >
template<>
struct DataType< ::donkey_car::IntValueResponse>
{
  static const char* value()
  {
    return DataType< ::donkey_car::IntValue >::value();
  }
  static const char* value(const ::donkey_car::IntValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DONKEY_CAR_MESSAGE_INTVALUE_H
