// Generated by gencpp from file donkey_car/ServoConfig.msg
// DO NOT EDIT!


#ifndef DONKEY_CAR_MESSAGE_SERVOCONFIG_H
#define DONKEY_CAR_MESSAGE_SERVOCONFIG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace donkey_car
{
template <class ContainerAllocator>
struct ServoConfig_
{
  typedef ServoConfig_<ContainerAllocator> Type;

  ServoConfig_()
    : servo(0)
    , center(0)
    , range(0)
    , direction(0)  {
    }
  ServoConfig_(const ContainerAllocator& _alloc)
    : servo(0)
    , center(0)
    , range(0)
    , direction(0)  {
  (void)_alloc;
    }



   typedef int16_t _servo_type;
  _servo_type servo;

   typedef int16_t _center_type;
  _center_type center;

   typedef int16_t _range_type;
  _range_type range;

   typedef int16_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::donkey_car::ServoConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::donkey_car::ServoConfig_<ContainerAllocator> const> ConstPtr;

}; // struct ServoConfig_

typedef ::donkey_car::ServoConfig_<std::allocator<void> > ServoConfig;

typedef boost::shared_ptr< ::donkey_car::ServoConfig > ServoConfigPtr;
typedef boost::shared_ptr< ::donkey_car::ServoConfig const> ServoConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::donkey_car::ServoConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::donkey_car::ServoConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::donkey_car::ServoConfig_<ContainerAllocator1> & lhs, const ::donkey_car::ServoConfig_<ContainerAllocator2> & rhs)
{
  return lhs.servo == rhs.servo &&
    lhs.center == rhs.center &&
    lhs.range == rhs.range &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::donkey_car::ServoConfig_<ContainerAllocator1> & lhs, const ::donkey_car::ServoConfig_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace donkey_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::donkey_car::ServoConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::donkey_car::ServoConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_car::ServoConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_car::ServoConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_car::ServoConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_car::ServoConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::donkey_car::ServoConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d258bdc7108a9660981de680cfa4372d";
  }

  static const char* value(const ::donkey_car::ServoConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd258bdc7108a9660ULL;
  static const uint64_t static_value2 = 0x981de680cfa4372dULL;
};

template<class ContainerAllocator>
struct DataType< ::donkey_car::ServoConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "donkey_car/ServoConfig";
  }

  static const char* value(const ::donkey_car::ServoConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::donkey_car::ServoConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the ServoConfig message is used to assign specific configuration\n"
"# data to a servo. the data is needed to normalize servos to\n"
"# common values to isolate variations from the rest of the user's\n"
"# robot motion code. \n"
"\n"
"int16 servo\n"
"int16 center\n"
"int16 range\n"
"int16 direction\n"
;
  }

  static const char* value(const ::donkey_car::ServoConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::donkey_car::ServoConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo);
      stream.next(m.center);
      stream.next(m.range);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::donkey_car::ServoConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::donkey_car::ServoConfig_<ContainerAllocator>& v)
  {
    s << indent << "servo: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo);
    s << indent << "center: ";
    Printer<int16_t>::stream(s, indent + "  ", v.center);
    s << indent << "range: ";
    Printer<int16_t>::stream(s, indent + "  ", v.range);
    s << indent << "direction: ";
    Printer<int16_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DONKEY_CAR_MESSAGE_SERVOCONFIG_H
