// Generated by gencpp from file donkey_car/ServosConfigRequest.msg
// DO NOT EDIT!


#ifndef DONKEY_CAR_MESSAGE_SERVOSCONFIGREQUEST_H
#define DONKEY_CAR_MESSAGE_SERVOSCONFIGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <donkey_car/ServoConfig.h>

namespace donkey_car
{
template <class ContainerAllocator>
struct ServosConfigRequest_
{
  typedef ServosConfigRequest_<ContainerAllocator> Type;

  ServosConfigRequest_()
    : servos()  {
    }
  ServosConfigRequest_(const ContainerAllocator& _alloc)
    : servos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::donkey_car::ServoConfig_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::donkey_car::ServoConfig_<ContainerAllocator> >> _servos_type;
  _servos_type servos;





  typedef boost::shared_ptr< ::donkey_car::ServosConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::donkey_car::ServosConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServosConfigRequest_

typedef ::donkey_car::ServosConfigRequest_<std::allocator<void> > ServosConfigRequest;

typedef boost::shared_ptr< ::donkey_car::ServosConfigRequest > ServosConfigRequestPtr;
typedef boost::shared_ptr< ::donkey_car::ServosConfigRequest const> ServosConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::donkey_car::ServosConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::donkey_car::ServosConfigRequest_<ContainerAllocator1> & lhs, const ::donkey_car::ServosConfigRequest_<ContainerAllocator2> & rhs)
{
  return lhs.servos == rhs.servos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::donkey_car::ServosConfigRequest_<ContainerAllocator1> & lhs, const ::donkey_car::ServosConfigRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace donkey_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::donkey_car::ServosConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_car::ServosConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_car::ServosConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f9c43713b493f265aec1e926dd292b8";
  }

  static const char* value(const ::donkey_car::ServosConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f9c43713b493f26ULL;
  static const uint64_t static_value2 = 0x5aec1e926dd292b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "donkey_car/ServosConfigRequest";
  }

  static const char* value(const ::donkey_car::ServosConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the servos_config service is used to assign useful configuration data to servos\n"
"# the tollerance of electronis varies in RC servos so it is important to calibate\n"
"# each servo, indicating its PWM value for direction of rotation, centering, and\n"
"# range which is used to scale servo motion a standard ±1000 scale\n"
"\n"
"ServoConfig[] servos\n"
"\n"
"================================================================================\n"
"MSG: donkey_car/ServoConfig\n"
"# the ServoConfig message is used to assign specific configuration\n"
"# data to a servo. the data is needed to normalize servos to\n"
"# common values to isolate variations from the rest of the user's\n"
"# robot motion code. \n"
"\n"
"int16 servo\n"
"int16 center\n"
"int16 range\n"
"int16 direction\n"
;
  }

  static const char* value(const ::donkey_car::ServosConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServosConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::donkey_car::ServosConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::donkey_car::ServosConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "servos[]" << std::endl;
    for (size_t i = 0; i < v.servos.size(); ++i)
    {
      s << indent << "  servos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::donkey_car::ServoConfig_<ContainerAllocator> >::stream(s, indent + "    ", v.servos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DONKEY_CAR_MESSAGE_SERVOSCONFIGREQUEST_H
