// Generated by gencpp from file donkey_car/StopServos.msg
// DO NOT EDIT!


#ifndef DONKEY_CAR_MESSAGE_STOPSERVOS_H
#define DONKEY_CAR_MESSAGE_STOPSERVOS_H

#include <ros/service_traits.h>


#include <donkey_car/StopServosRequest.h>
#include <donkey_car/StopServosResponse.h>


namespace donkey_car
{

struct StopServos
{

typedef StopServosRequest Request;
typedef StopServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopServos
} // namespace donkey_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::donkey_car::StopServos > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::donkey_car::StopServos&) { return value(); }
};

template<>
struct DataType< ::donkey_car::StopServos > {
  static const char* value()
  {
    return "donkey_car/StopServos";
  }

  static const char* value(const ::donkey_car::StopServos&) { return value(); }
};


// service_traits::MD5Sum< ::donkey_car::StopServosRequest> should match
// service_traits::MD5Sum< ::donkey_car::StopServos >
template<>
struct MD5Sum< ::donkey_car::StopServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::StopServos >::value();
  }
  static const char* value(const ::donkey_car::StopServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::StopServosRequest> should match
// service_traits::DataType< ::donkey_car::StopServos >
template<>
struct DataType< ::donkey_car::StopServosRequest>
{
  static const char* value()
  {
    return DataType< ::donkey_car::StopServos >::value();
  }
  static const char* value(const ::donkey_car::StopServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::donkey_car::StopServosResponse> should match
// service_traits::MD5Sum< ::donkey_car::StopServos >
template<>
struct MD5Sum< ::donkey_car::StopServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_car::StopServos >::value();
  }
  static const char* value(const ::donkey_car::StopServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_car::StopServosResponse> should match
// service_traits::DataType< ::donkey_car::StopServos >
template<>
struct DataType< ::donkey_car::StopServosResponse>
{
  static const char* value()
  {
    return DataType< ::donkey_car::StopServos >::value();
  }
  static const char* value(const ::donkey_car::StopServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DONKEY_CAR_MESSAGE_STOPSERVOS_H
