(cl:defpackage your_smach-srv
  (:use )
  (:export
   "GOTOPOSITION"
   "<GOTOPOSITION-REQUEST>"
   "GOTOPOSITION-REQUEST"
   "<GOTOPOSITION-RESPONSE>"
   "GOTOPOSITION-RESPONSE"
   "TRIGGER"
   "<TRIGGER-REQUEST>"
   "TRIGGER-REQUEST"
   "<TRIGGER-RESPONSE>"
   "TRIGGER-RESPONSE"
  ))

