// Generated by gencpp from file your_package/NavToLocation.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_NAVTOLOCATION_H
#define YOUR_PACKAGE_MESSAGE_NAVTOLOCATION_H

#include <ros/service_traits.h>


#include <your_package/NavToLocationRequest.h>
#include <your_package/NavToLocationResponse.h>


namespace your_package
{

struct NavToLocation
{

typedef NavToLocationRequest Request;
typedef NavToLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavToLocation
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::NavToLocation > {
  static const char* value()
  {
    return "3a4956001e76e70331ffcf62ffc6a8d5";
  }

  static const char* value(const ::your_package::NavToLocation&) { return value(); }
};

template<>
struct DataType< ::your_package::NavToLocation > {
  static const char* value()
  {
    return "your_package/NavToLocation";
  }

  static const char* value(const ::your_package::NavToLocation&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::NavToLocationRequest> should match
// service_traits::MD5Sum< ::your_package::NavToLocation >
template<>
struct MD5Sum< ::your_package::NavToLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::NavToLocation >::value();
  }
  static const char* value(const ::your_package::NavToLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::NavToLocationRequest> should match
// service_traits::DataType< ::your_package::NavToLocation >
template<>
struct DataType< ::your_package::NavToLocationRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::NavToLocation >::value();
  }
  static const char* value(const ::your_package::NavToLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::NavToLocationResponse> should match
// service_traits::MD5Sum< ::your_package::NavToLocation >
template<>
struct MD5Sum< ::your_package::NavToLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::NavToLocation >::value();
  }
  static const char* value(const ::your_package::NavToLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::NavToLocationResponse> should match
// service_traits::DataType< ::your_package::NavToLocation >
template<>
struct DataType< ::your_package::NavToLocationResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::NavToLocation >::value();
  }
  static const char* value(const ::your_package::NavToLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_NAVTOLOCATION_H
