// Generated by gencpp from file your_package/SaveLocation.msg
// DO NOT EDIT!


#ifndef YOUR_PACKAGE_MESSAGE_SAVELOCATION_H
#define YOUR_PACKAGE_MESSAGE_SAVELOCATION_H

#include <ros/service_traits.h>


#include <your_package/SaveLocationRequest.h>
#include <your_package/SaveLocationResponse.h>


namespace your_package
{

struct SaveLocation
{

typedef SaveLocationRequest Request;
typedef SaveLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveLocation
} // namespace your_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::your_package::SaveLocation > {
  static const char* value()
  {
    return "3a4956001e76e70331ffcf62ffc6a8d5";
  }

  static const char* value(const ::your_package::SaveLocation&) { return value(); }
};

template<>
struct DataType< ::your_package::SaveLocation > {
  static const char* value()
  {
    return "your_package/SaveLocation";
  }

  static const char* value(const ::your_package::SaveLocation&) { return value(); }
};


// service_traits::MD5Sum< ::your_package::SaveLocationRequest> should match
// service_traits::MD5Sum< ::your_package::SaveLocation >
template<>
struct MD5Sum< ::your_package::SaveLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::SaveLocation >::value();
  }
  static const char* value(const ::your_package::SaveLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SaveLocationRequest> should match
// service_traits::DataType< ::your_package::SaveLocation >
template<>
struct DataType< ::your_package::SaveLocationRequest>
{
  static const char* value()
  {
    return DataType< ::your_package::SaveLocation >::value();
  }
  static const char* value(const ::your_package::SaveLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::your_package::SaveLocationResponse> should match
// service_traits::MD5Sum< ::your_package::SaveLocation >
template<>
struct MD5Sum< ::your_package::SaveLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::your_package::SaveLocation >::value();
  }
  static const char* value(const ::your_package::SaveLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::your_package::SaveLocationResponse> should match
// service_traits::DataType< ::your_package::SaveLocation >
template<>
struct DataType< ::your_package::SaveLocationResponse>
{
  static const char* value()
  {
    return DataType< ::your_package::SaveLocation >::value();
  }
  static const char* value(const ::your_package::SaveLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOUR_PACKAGE_MESSAGE_SAVELOCATION_H
